apiVersion: v1
kind: ServiceAccount
metadata:
  name: mongodb-database
  labels:
    {{- include "mongodb.labels" . | nindent 4 }}
{{- if .Values.global.imagePullSecrets }}
imagePullSecrets:
  {{- toYaml .Values.global.imagePullSecrets | nindent 2 }}
{{- end }}
