apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "tapdata-server.fullname" . }}-wait-mdb
  labels:
    {{- include "tapdata-server.labels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "tapdata-server.fullname" . }}-wait-mdb
  labels:
    {{- include "tapdata-server.labels" . | nindent 4 }}
rules:
  - apiGroups: ["mongodbcommunity.mongodb.com"]
    resources: ["mongodbcommunity"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "tapdata-server.fullname" . }}-wait-mdb
  labels:
    {{- include "tapdata-server.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "tapdata-server.fullname" . }}-wait-mdb
roleRef:
  kind: Role
  name: {{ include "tapdata-server.fullname" . }}-wait-mdb
  apiGroup: rbac.authorization.k8s.io
