global:
  mongodb:
    replicaSetName: tapdata-mongodb
    protocol: mongodb
    user: root
    password: AbcDef123
    authSource: admin
    database: tapdata
    hosts: "tapdata-mongodb-0.tapdata-mongodb-svc:27017,tapdata-mongodb-1.tapdata-mongodb-svc:27017,tapdata-mongodb-2.tapdata-mongodb-svc:27017"
  imagePullSecret:
    enabled: true
    name: ""
    registry: ""
    username: ""
    password: ""

replicaCount: 2

image:
  repository: tapdata8/tapdata
  tag: latest
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

resources:
  limits:
    cpu: 2000m
    memory: 4Gi
  requests:
    cpu: 500m
    memory: 2Gi

env:
  module: backend
  backendUrl: "http://tapdata-server-svr:3030/api/"
  javaVersion: java17
  tz: Asia/Shanghai
  licenseHost: "113.98.206.142:18080"

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

nodeSelector: {}

tolerations: []

affinity: {}
